#spring:
#  application:
#    name: sprbasic2025summer
#  config:
#    import:
#      - classpath:/yaml/application-keys.yaml

debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.thc.sprbasic2025summer: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  config:
    import:
      - classpath:/yaml/application-keys.yaml
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    remote:
      restart:
        enabled: false
  freemarker:
    cache: false
  sql.init.mode: always
  #sql.init.mode: never